### ISSUE TITLE
eddy_cuda in mrtrix's dwifslpreproc 

### ISSUE THREAD

**Issue by zklsmr** [DouglasNeuroInformatics/software_quarantine#21]
Eddy_cuda from mrtrix's dwifslpreproc does not work, gives the error

`eddy_cuda10.2: error while loading shared libraries: libcublas.so.10: cannot open shared object file: No such file or directory`

Relevant posts:
https://community.mrtrix.org/t/problems-with-cuda-version-when-running-eddy-cuda/4292
https://community.mrtrix.org/t/eddy-cuda-was-unsuccesful-attempting-openmp/5992/7

**Comment by gdevenyi** [comment]
Did you `module load cuda/10.2`?

**Comment by zklsmr** [comment]
Nope, but now I did and it works perfectly! 

Thanks for the quick response, this issue is solved!
