### ISSUE TITLE
R package request

### ISSUE THREAD

**Issue by yasharz** [DouglasNeuroInformatics/software_quarantine#5]
Is it possible to add 'SeuratObject' (https://cran.r-project.org/web/packages/SeuratObject/index.html , https://github.com/mojaveazure/seurat-object)

I get the following error:
Loading required package: SeuratObject
Error in .requirePackage(package) : 
  unable to find required package ‘SeuratObject’
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘SeuratObject’
Loading required package: SeuratObject
Error during wrapup: unable to find required package ‘SeuratObject’
Error: no more error handlers available (recursive errors?); invoking 'abort' restart

**Comment by gdevenyi** [comment]
Installed.
