### ISSUE TITLE
R library edgebundle

### ISSUE THREAD

**Issue by yasharz** [DouglasNeuroInformatics/software_quarantine#7]
Hi 

Is it possible to install edgebundle ?

This is the suggested installation from the page I am using

library(devtools)
# Install edgebundle package from GitHub
install_github("garthtarr/edgebundle")

**Comment by yasharz** [comment]
sorry I mistyped it is edgebundleR .
Is it possible to also install "svglite"

**Comment by gdevenyi** [comment]
Done and Done
