### ISSUE TITLE
more R library requests

### ISSUE THREAD

**Issue by yasharz** [DouglasNeuroInformatics/software_quarantine#8]
Hi,

Is it possible to install the following R libraries:

Seurat : https://satijalab.org/seurat/articles/install.html
Signac : https://stuartlab.org/signac/articles/install.html
R.matlab : https://cran.r-project.org/web/packages/R.matlab/index.html

Best

**Comment by gdevenyi** [comment]
working on this, the bioconda package repository seems to have some breakage right now preventing installation

**Comment by gdevenyi** [comment]
Installed in R/4.2.0 module.
